apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: shteou
    provider: github
    repository: test-service
  name: shteou-test-service
spec:
  description: Imported application for shteou/test-service
  httpCloneURL: https://github.com/shteou/test-service.git
  org: shteou
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: test-service
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/shteou/test-service.git
